name: Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TEALBASE_ACCESS_TOKEN: ${{ secrets.TEALBASE_ACCESS_TOKEN }}
      TEALBASE_PROJECT_ID: ${{ secrets.TEALBASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: tealbase/setup-cli@v1
        with:
          version: latest

      - run: tealbase functions deploy --project-ref $TEALBASE_PROJECT_ID